"""added audio ID

Revision ID: 38ba4ae9cae2
Revises: dc3ac879d582
Create Date: 2025-11-25 09:32:03.660399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38ba4ae9cae2'
down_revision: Union[str, Sequence[str], None] = 'dc3ac879d582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiosample', sa.Column('audio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiosample', 'audio_id')
    # ### end Alembic commands ###
